# Generated by Django 4.2.2 on 2023-09-17 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tech_techusage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techusage',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='techusage',
            old_name='tech_id',
            new_name='tech',
        ),
    ]
